// POST /api/builder/inquiry
// Submits a customer inquiry. No auth required — public endpoint.

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { createServiceClient } from '../../../lib/supabase-server'
import { sendNewInquiryEmail, sendInquiryConfirmationEmail } from '../../../lib/email'
import type { ApiResponse, SubmitInquiryPayload } from '../../../types'

const InquirySchema = z.object({
  account_id: z.string().uuid(),
  customer_name: z.string().min(1).max(200),
  customer_email: z.string().email(),
  customer_phone: z.string().optional(),
  ring_type: z.string().optional(),
  selections: z.record(z.unknown()).optional(),
  inspiration_photo_url: z.string().url().optional(),
  ring_size: z.string().optional(),
  band_width: z.string().optional(),
  budget_range: z.string().optional(),
  timeline: z.string().optional(),
  notes: z.string().max(2000).optional(),
  ai_chat_transcript: z.array(z.object({
    role: z.enum(['user', 'assistant']),
    content: z.string(),
  })).optional(),
  source_url: z.string().url().optional(),
})

export async function POST(request: NextRequest) {
  let body: SubmitInquiryPayload
  try {
    body = await request.json()
  } catch {
    return NextResponse.json<ApiResponse>({ error: 'Invalid JSON' }, { status: 400 })
  }

  const parsed = InquirySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json<ApiResponse>(
      { error: parsed.error.issues[0]?.message || 'Validation failed' },
      { status: 422 }
    )
  }

  const data = parsed.data
  const supabase = createServiceClient()

  // Verify account exists and is active
  const { data: account, error: accountError } = await supabase
    .from('accounts')
    .select('id, email, business_name, notification_email, subdomain, status, plan')
    .eq('id', data.account_id)
    .single()

  if (accountError || !account) {
    return NextResponse.json<ApiResponse>({ error: 'Invalid account' }, { status: 404 })
  }

  if (account.status === 'suspended' || account.status === 'cancelled') {
    return NextResponse.json<ApiResponse>({ error: 'Account inactive' }, { status: 403 })
  }

  // Check inquiry limit for plan
  // (reference_code is auto-generated by the DB trigger)
  const { data: inquiry, error: insertError } = await supabase
    .from('inquiries')
    .insert({
      account_id: data.account_id,
      status: 'new',
      customer_name: data.customer_name,
      customer_email: data.customer_email,
      customer_phone: data.customer_phone,
      ring_type: data.ring_type,
      selections: data.selections || {},
      inspiration_photo_url: data.inspiration_photo_url,
      ring_size: data.ring_size,
      band_width: data.band_width,
      budget_range: data.budget_range,
      timeline: data.timeline,
      notes: data.notes,
      ai_chat_transcript: data.ai_chat_transcript || [],
      source_url: data.source_url,
    })
    .select()
    .single()

  if (insertError || !inquiry) {
    console.error('Inquiry insert error:', insertError)
    return NextResponse.json<ApiResponse>({ error: 'Failed to save inquiry' }, { status: 500 })
  }

  // Log the creation event
  await supabase.from('inquiry_events').insert({
    inquiry_id: inquiry.id,
    account_id: account.id,
    actor: 'customer',
    event_type: 'created',
    payload: { reference_code: inquiry.reference_code },
  })

  // Send emails (non-blocking — don't fail the request if email fails)
  Promise.all([
    sendNewInquiryEmail(inquiry, account).catch(console.error),
    sendInquiryConfirmationEmail(inquiry, account).catch(console.error),
  ])

  return NextResponse.json<ApiResponse>(
    { data: { reference_code: inquiry.reference_code, id: inquiry.id } },
    { status: 201 }
  )
}
