'use client'
import { useState, useEffect } from 'react'

const G='#B5966D',GD='#8A6D48',GP='#FAF5EE',INK='#1C1612',INKS='#9C8470',INKG='#C8B8A8',W='#FFFFFF',BDR='rgba(181,150,109,0.18)',BDRS='rgba(181,150,109,0.35)'
const SC:any={Diamond:'#E8F4FF',Sapphire:'#C5D8F0',Emerald:'#C8E8D0',Ruby:'#FAD0D0',Morganite:'#FAE0EC',Moissanite:'#EEEDFE'}
const MC:any={'Yellow Gold':'#E8C45A','White Gold':'#D8D8E4','Rose Gold':'#E8A48A','Platinum':'#C4C4D4','Two-Tone':'#D4B870'}
const SZ:any={'0.5 ct':18,'0.75 ct':22,'1.0 ct':27,'1.5 ct':31,'2.0 ct':35,'2.5+ ct':38}
const CC:any={Diamond:'#E8F4FF',Sapphire:'#C5D8F0',Emerald:'#C8E8D0',Ruby:'#FAD0D0',Morganite:'#FAE0EC',Moissanite:'#EEEDFE','Yellow Gold':'#E8C45A','White Gold':'#D8D8E4','Rose Gold':'#E8A48A','Platinum':'#C4C4D4','Two-Tone':'#D4B870'}
const DEFAULT:any={stone:[{v:'Diamond',sub:'Classic brilliance',c:'#E8F4FF'},{v:'Sapphire',sub:'Deep royal blue',c:'#C5D8F0'},{v:'Emerald',sub:'Rich vivid green',c:'#C8E8D0'},{v:'Ruby',sub:'Passionate red',c:'#FAD0D0'},{v:'Morganite',sub:'Soft blush pink',c:'#FAE0EC'},{v:'Moissanite',sub:'Eco-friendly',c:'#EEEDFE'}],shape:[{v:'Round',sub:'Most brilliant'},{v:'Princess',sub:'Bold & modern'},{v:'Oval',sub:'Elongates finger'},{v:'Cushion',sub:'Soft & romantic'},{v:'Marquise',sub:'Dramatic'},{v:'Pear',sub:'Elegant teardrop'},{v:'Emerald cut',sub:'Art deco'},{v:'Radiant',sub:'Brilliant & fiery'}],carat:[{v:'0.5 ct',sub:'Subtle',sz:18},{v:'0.75 ct',sub:'Popular',sz:22},{v:'1.0 ct',sub:'Benchmark',sz:27},{v:'1.5 ct',sub:'Eye-catching',sz:31},{v:'2.0 ct',sub:'Bold',sz:35},{v:'2.5+ ct',sub:'Maximum',sz:38}],setting:[{v:'Solitaire',sub:'Timeless'},{v:'Halo',sub:'Surrounded by sparkle'},{v:'Pavé',sub:'Diamond-lined'},{v:'Three Stone',sub:'Past present future'},{v:'Bezel',sub:'Modern'},{v:'Vintage',sub:'Ornate'}],metal:[{v:'Yellow Gold',sub:'Classic & warm',c:'#E8C45A'},{v:'White Gold',sub:'Modern & sleek',c:'#D8D8E4'},{v:'Rose Gold',sub:'Romantic & warm',c:'#E8A48A'},{v:'Platinum',sub:'Premium',c:'#C4C4D4'},{v:'Two-Tone',sub:'Mixed metals',c:'#D4B870'}],band:[{v:'Plain',sub:'Minimal'},{v:'Twisted',sub:'Braided'},{v:'Eternity',sub:'Diamonds around'},{v:'Milgrain',sub:'Vintage edge'},{v:'Cathedral',sub:'Arched'},{v:'Split Shank',sub:'Fork design'}],enh:[{v:'Engraving',sub:'Message inside'},{v:'Side stones',sub:'On the shank'},{v:'Filigree',sub:'Metalwork'},{v:'Conflict-free cert.',sub:'Ethical'},{v:'Hidden halo',sub:'Secret sparkle'},{v:'Rush production',sub:'Priority'}]}

export default function Page({params}:{params:{subdomain:string}}){
  const T=13
  const [cur,setCur]=useState(1)
  const [R,setR]=useState<any>({})
  const [contact,setContact]=useState({first:'',last:'',email:'',phone:''})
  const [prefs,setPrefs]=useState({size:'',width:'',budget:'',timeline:'',notes:''})
  const [enh,setEnh]=useState<string[]>([])
  const [done,setDone]=useState(false)
  const [ref,setRef]=useState('')
  const [opts,setOpts]=useState<any>(DEFAULT)
  const [accountId,setAccountId]=useState<string>('8433f769-632e-4426-b07b-0f5c9e7a2fe6')
  const [loading,setLoading]=useState(true)

  useEffect(()=>{
    fetch(`/api/builder/config?subdomain=${params.subdomain}`)
      .then(r=>r.json())
      .then(json=>{
        if(json.data?.account?.id){
          setAccountId(json.data.account.id)
          const o=json.data.options
          const mapped:any={}
          Object.keys(o).forEach(key=>{
            mapped[key]=o[key].map((item:any)=>({
              v:item.label,
              sub:item.description||'',
              c:item.color_hex||CC[item.label]||'#F7F0E8',
              sz:SZ[item.label]||27,
              img:item.image_url||null
            }))
          })
          if(Object.keys(mapped).length>0)setOpts({...DEFAULT,...mapped})
        }
      })
      .catch(()=>{})
      .finally(()=>setLoading(false))
  },[params.subdomain])

  const set=(k:string,v:string)=>setR((p:any)=>({...p,[k]:v}))
  const next=()=>{if(cur===1&&(!contact.first||!contact.email)){alert('Please enter your name and email.');return}if(cur<T)setCur(c=>c+1)}
  const prev=()=>{if(cur>1)setCur(c=>c-1)}
  const tog=(v:string)=>setEnh(p=>p.includes(v)?p.filter((x:string)=>x!==v):[...p,v])

  const submit=async()=>{
    try{
      const res=await fetch('/api/builder/inquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account_id:accountId,customer_name:(contact.first+' '+contact.last).trim(),customer_email:contact.email,customer_phone:contact.phone||null,ring_type:R.type||null,selections:R,ring_size:prefs.size||null,band_width:prefs.width||null,budget_range:prefs.budget||null,timeline:prefs.timeline||null,notes:prefs.notes||null,source_url:window.location.href})})
      const json=await res.json()
      setRef(json.data?.reference_code||'RNG-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*9000)+1000))
    }catch(e){
      setRef('RNG-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*9000)+1000))
    }
    setDone(true)
  }

  const inp={width:'100%',padding:'9px 12px',fontSize:14,border:'1px solid '+BDRS,borderRadius:8,background:W,color:INK,outline:'none',fontFamily:'inherit'} as any
  const bn={background:G,border:'none',borderRadius:8,padding:'10px 22px',fontSize:13,fontWeight:500,color:'#fff',cursor:'pointer',marginLeft:'auto',fontFamily:'inherit'} as any
  const bb={background:'transparent',border:'1px solid '+BDRS,borderRadius:8,padding:'10px 18px',fontSize:13,color:INKS,cursor:'pointer',fontFamily:'inherit'} as any
  const SH=({n,t,s}:{n:number,t:string,s:string})=><div style={{marginBottom:'1.25rem'}}><div style={{fontSize:10,color:G,textTransform:'uppercase',letterSpacing:'.1em',fontWeight:500,marginBottom:5}}>Step {n} of {T}</div><div style={{fontFamily:'Georgia,serif',fontSize:26,fontWeight:300,color:INK,marginBottom:4}}>{t}</div><div style={{fontSize:13,color:INKS}}>{s}</div></div>
  const Nav=({dis,lbl}:{dis?:boolean,lbl?:string})=><div style={{display:'flex',gap:8,marginTop:'1.5rem'}}>{cur>1&&<button style={bb} onClick={prev}>← Back</button>}<button style={{...bn,opacity:dis?.35:1,marginLeft:'auto'}} disabled={dis} onClick={next}>{lbl||'Continue →'}</button></div>
  const Grid=({items,sel,onSel,svg}:{items:any[],sel:string,onSel:(v:string)=>void,svg:(i:any)=>any})=><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(130px,1fr))',gap:10}}>{items.map((item:any)=><div key={item.v} onClick={()=>onSel(item.v)} style={{background:W,border:sel===item.v?'2px solid '+G:'1px solid '+BDR,borderRadius:12,cursor:'pointer',overflow:'hidden'}}><div style={{width:'100%',aspectRatio:'1',background:GP,display:'flex',alignItems:'center',justifyContent:'center',padding:10}}>{svg(item)}</div><div style={{padding:'7px 10px 3px',fontSize:12,fontWeight:500,color:INK}}>{item.v}</div><div style={{padding:'0 10px 8px',fontSize:11,color:INKS}}>{item.sub}</div></div>)}</div>

  if(loading)return<div style={{minHeight:'100vh',background:'#F8F3EC',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{fontFamily:'Georgia,serif',fontSize:20,color:INKS}}>Loading your ring builder…</div></div>
  if(done)return<div style={{minHeight:'100vh',background:'#F8F3EC',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{textAlign:'center',padding:'3rem 1rem'}}><div style={{fontSize:52,marginBottom:16}}>✨</div><div style={{fontFamily:'Georgia,serif',fontSize:30,fontWeight:300,color:INK,marginBottom:8}}>Inquiry submitted!</div><div style={{fontSize:14,color:INKS,lineHeight:1.7,maxWidth:360,margin:'0 auto 1.5rem'}}>A master jeweller will be in touch within 24 hours.</div><div style={{background:W,border:'1px solid '+BDR,borderRadius:12,padding:'14px 20px',display:'inline-block'}}><div style={{fontSize:10,color:INKS,textTransform:'uppercase',letterSpacing:'.08em',marginBottom:4}}>Reference</div><div style={{fontFamily:'Georgia,serif',fontSize:20,color:G}}>{ref}</div></div></div></div>

  return<div style={{minHeight:'100vh',background:'#F8F3EC'}}>
    <div style={{padding:'0 1.25rem',height:50,background:W,borderBottom:'1px solid '+BDR,display:'flex',alignItems:'center',position:'sticky',top:0,zIndex:50}}><div style={{fontFamily:'Georgia,serif',fontSize:20,color:INK}}>Ring<span style={{color:G}}>Studio</span></div></div>
    <div style={{maxWidth:660,margin:'0 auto',padding:'1.5rem 1rem 4rem'}}>
      <div style={{display:'flex',alignItems:'center',gap:4,marginBottom:'1.5rem',flexWrap:'wrap'}}>{Array.from({length:T}).map((_,i)=><div key={i} style={{width:i+1===cur?18:5,height:5,borderRadius:i+1===cur?3:'50%',background:i<cur?G:INKG,transition:'all .25s',flexShrink:0}}/>)}<span style={{fontSize:11,color:INKG,marginLeft:6}}>Step {cur} of {T}</span></div>
      {cur>1&&[R.type,R.stone,R.shape,R.metal].filter(Boolean).length>0&&<div style={{display:'flex',alignItems:'center',gap:12,padding:'10px 14px',background:W,border:'1px solid '+BDR,borderRadius:12,marginBottom:'1.25rem'}}><span style={{fontSize:22}}>💍</span><div style={{flex:1,minWidth:0}}><div style={{fontSize:10,color:INKG,textTransform:'uppercase',letterSpacing:'.07em'}}>Your ring so far</div><div style={{fontSize:13,fontWeight:500,color:INK,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{[R.type,R.stone,R.shape,R.metal].filter(Boolean).join(' · ')}</div></div></div>}
      {cur===1&&<div><SH n={1} t="Let's start with your details" s="We'll use this to send your personalised quote."/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div style={{marginBottom:12}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>First name</label><input style={inp} value={contact.first} onChange={(e:any)=>setContact(p=>({...p,first:e.target.value}))} placeholder="Jane"/></div><div style={{marginBottom:12}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Last name</label><input style={inp} value={contact.last} onChange={(e:any)=>setContact(p=>({...p,last:e.target.value}))} placeholder="Smith"/></div></div><div style={{marginBottom:12}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Email</label><input style={inp} type="email" value={contact.email} onChange={(e:any)=>setContact(p=>({...p,email:e.target.value}))} placeholder="jane@example.com"/></div><div style={{marginBottom:12}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Phone</label><input style={inp} type="tel" value={contact.phone} onChange={(e:any)=>setContact(p=>({...p,phone:e.target.value}))} placeholder="+1 (416) 555-0100"/></div><Nav dis={!contact.first||!contact.email}/></div>}
      {cur===2&&<div><SH n={2} t="What are you designing?" s="Choose the type of ring you have in mind."/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{[{v:'Engagement Ring',i:'💍',d:'A centrepiece stone ring.'},{v:'Wedding Band',i:'⭕',d:'A band for your wedding day.'}].map((t:any)=><div key={t.v} onClick={()=>set('type',t.v)} style={{background:R.type===t.v?GP:W,border:R.type===t.v?'2px solid '+G:'1px solid '+BDR,borderRadius:14,padding:'22px 16px',cursor:'pointer',textAlign:'center'}}><div style={{fontSize:36,marginBottom:10}}>{t.i}</div><div style={{fontFamily:'Georgia,serif',fontSize:19,color:INK,marginBottom:5}}>{t.v}</div><div style={{fontSize:12,color:INKS}}>{t.d}</div></div>)}</div><Nav dis={!R.type}/></div>}
      {cur===3&&<div><SH n={3} t="Have an inspiration photo?" s="Upload a picture or continue from scratch."/><div onClick={()=>set('photo','uploaded')} style={{border:'1px dashed '+BDRS,borderRadius:12,padding:'2.5rem 2rem',textAlign:'center',background:W,cursor:'pointer'}}><div style={{fontSize:32,marginBottom:10}}>📷</div><div style={{fontSize:14,fontWeight:500,color:INKS}}>Click to upload a photo</div></div><div style={{display:'flex',alignItems:'center',gap:12,margin:'1rem 0'}}><div style={{flex:1,height:1,background:BDR}}/><span style={{fontSize:11,color:INKG}}>OR</span><div style={{flex:1,height:1,background:BDR}}/></div><button onClick={()=>{set('photo','none');setCur(4)}} style={{width:'100%',background:W,border:'1px solid '+BDRS,borderRadius:8,padding:12,fontSize:14,color:INKS,cursor:'pointer',fontFamily:'inherit'}}>🪄 Continue with the wizard</button><Nav dis={false} lbl="Skip →"/></div>}
      {cur===4&&<div><SH n={4} t="Choose your centre stone" s="Select the gemstone that speaks to you."/><Grid items={opts.stone||[]} sel={R.stone||''} onSel={v=>set('stone',v)} svg={(i:any)=><svg viewBox="0 0 80 80" fill="none" width="100%" height="100%"><polygon points="40,10 70,34 40,70 10,34" fill={i.c||'#E8F4FF'} stroke="#85B7EB" strokeWidth="1.5"/><polygon points="40,10 70,34 40,34" fill={i.c||'#E8F4FF'} stroke="#85B7EB" strokeWidth="1" opacity=".7"/></svg>}/><Nav dis={!R.stone}/></div>}
      {cur===5&&<div><SH n={5} t="Choose your stone shape" s="Each shape has its own personality."/><Grid items={opts.shape||[]} sel={R.shape||''} onSel={v=>set('shape',v)} svg={(i:any)=><svg viewBox="0 0 80 80" fill="none" width="100%" height="100%"><circle cx="40" cy="40" r="28" fill="#F7F0E8" stroke={G} strokeWidth="1.5"/><text x="40" y="44" fontSize="8" textAnchor="middle" fill={GD}>{i.v.slice(0,3)}</text></svg>}/><Nav dis={!R.shape}/></div>}
      {cur===6&&<div><SH n={6} t="Select carat weight" s="Larger carats appear bigger on the finger."/><Grid items={opts.carat||[]} sel={R.carat||''} onSel={v=>set('carat',v)} svg={(i:any)=><svg viewBox="0 0 80 80" fill="none" width="100%" height="100%"><circle cx="40" cy="40" r={i.sz||27} fill="#F7F0E8" stroke={G} strokeWidth="1.5"/><circle cx="40" cy="40" r={Math.round((i.sz||27)*.55)} fill="#EDE0CC" stroke={G} strokeWidth="1"/></svg>}/><Nav dis={!R.carat}/></div>}
      {cur===7&&<div><SH n={7} t="Setting style" s="The setting defines how your stone is held."/><Grid items={opts.setting||[]} sel={R.setting||''} onSel={v=>set('setting',v)} svg={()=><div style={{fontSize:28,display:'flex',alignItems:'center',justifyContent:'center',width:'100%',height:'100%'}}>✨</div>}/><Nav dis={!R.setting}/></div>}
      {cur===8&&<div><SH n={8} t="Metal type" s="The metal sets the tone and durability."/><Grid items={opts.metal||[]} sel={R.metal||''} onSel={v=>set('metal',v)} svg={(i:any)=><svg viewBox="0 0 80 80" fill="none" width="100%" height="100%"><circle cx="40" cy="40" r="30" fill={i.c||'#E8C45A'} stroke={G} strokeWidth="1.5"/><circle cx="40" cy="40" r="18" fill={i.c||'#E8C45A'} stroke={G} strokeWidth="1" opacity=".6"/></svg>}/><Nav dis={!R.metal}/></div>}
      {cur===9&&<div><SH n={9} t="Band design" s="Choose the style of the band itself."/><Grid items={opts.band||[]} sel={R.band||''} onSel={v=>set('band',v)} svg={()=><div style={{fontSize:28,display:'flex',alignItems:'center',justifyContent:'center',width:'100%',height:'100%'}}>⭕</div>}/><Nav dis={!R.band}/></div>}
      {cur===10&&<div><SH n={10} t="Optional enhancements" s="Select all that apply."/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(148px,1fr))',gap:10}}>{(opts.enh||[]).map((e:any)=><div key={e.v} onClick={()=>tog(e.v)} style={{background:enh.includes(e.v)?GP:W,border:enh.includes(e.v)?'2px solid '+G:'1px solid '+BDR,borderRadius:12,padding:13,cursor:'pointer'}}><div style={{fontSize:20,marginBottom:6}}>✨</div><div style={{fontSize:13,fontWeight:500,color:INK,marginBottom:2}}>{e.v}</div><div style={{fontSize:11,color:INKS}}>{e.sub}</div></div>)}</div><Nav/></div>}
      {cur===11&&<div><SH n={11} t="Final preferences" s="Help us match the perfect ring."/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:10}}><div><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Ring size</label><select style={inp} value={prefs.size} onChange={(e:any)=>setPrefs(p=>({...p,size:e.target.value}))}><option value="">Select</option>{['4','4.5','5','5.5','6','6.5','7','7.5','8','8.5','9','Not sure'].map(v=><option key={v}>{v}</option>)}</select></div><div><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Budget</label><select style={inp} value={prefs.budget} onChange={(e:any)=>setPrefs(p=>({...p,budget:e.target.value}))}><option value="">Select</option>{['Under $1,000','$1,000–$2,500','$2,500–$5,000','$5,000–$10,000','$10,000–$20,000','$20,000+'].map(v=><option key={v}>{v}</option>)}</select></div></div><div style={{marginBottom:10}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Timeline</label><select style={inp} value={prefs.timeline} onChange={(e:any)=>setPrefs(p=>({...p,timeline:e.target.value}))}><option value="">Select</option>{['As soon as possible','Within 2 weeks','1–2 months','3–6 months','6+ months','Just browsing'].map(v=><option key={v}>{v}</option>)}</select></div><div style={{marginBottom:10}}><label style={{display:'block',fontSize:11,color:INKS,textTransform:'uppercase',letterSpacing:'.07em',marginBottom:4}}>Notes</label><textarea style={{...inp,resize:'vertical',minHeight:80,fontSize:13}} value={prefs.notes} onChange={(e:any)=>setPrefs(p=>({...p,notes:e.target.value}))} placeholder="Special requests..."/></div><Nav/></div>}
      {cur===12&&<div><SH n={12} t="Review your design" s="Everything looks right?"/><div style={{background:W,border:'1px solid '+BDR,borderRadius:12,overflow:'hidden',marginBottom:'1.25rem'}}>{[['Name',(contact.first+' '+contact.last).trim()],['Email',contact.email],['Phone',contact.phone||'—'],['Ring type',R.type],['Stone',R.stone],['Shape',R.shape],['Carat',R.carat],['Setting',R.setting],['Metal',R.metal],['Band',R.band],['Enhancements',enh.length?enh.join(', '):'None'],['Budget',prefs.budget||'—'],['Timeline',prefs.timeline||'—']].map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between',padding:'9px 16px',borderBottom:'1px solid '+BDR,fontSize:13}}><span style={{color:INKS}}>{k}</span><span style={{fontWeight:500,color:INK,textAlign:'right',maxWidth:'60%'}}>{v||'—'}</span></div>)}</div><Nav lbl="See my ring →"/></div>}
      {cur===13&&<div><SH n={13} t="Your ring" s="Here's your custom design."/><div style={{background:W,border:'1px solid '+BDR,borderRadius:14,padding:'2rem',textAlign:'center',marginBottom:'1.25rem'}}><svg viewBox="0 0 220 200" fill="none" style={{width:'100%',maxWidth:200,display:'block',margin:'0 auto'}}><ellipse cx="110" cy="183" rx="55" ry="8" fill="rgba(0,0,0,.07)"/><ellipse cx="110" cy="168" rx="72" ry="17" fill={MC[R.metal]||'#EDE0CC'} stroke={G} strokeWidth="1.5"/><rect x="38" y="145" width="144" height="28" rx="14" fill={MC[R.metal]||'#EDE0CC'} stroke={G} strokeWidth="1.5"/><rect x="80" y="65" width="60" height="86" rx="6" fill={MC[R.metal]||'#EDE0CC'} stroke={G} strokeWidth="1.5"/><polygon points="110,12 148,56 110,82 72,56" fill={SC[R.stone]||'#F7F0E8'} stroke={G} strokeWidth="1.5"/><polygon points="110,12 148,56 110,42" fill={SC[R.stone]||'#F7F0E8'} stroke={G} strokeWidth="1" opacity=".7"/><polygon points="110,42 148,56 110,82" fill={SC[R.stone]||'#F7F0E8'} stroke={G} strokeWidth="1" opacity=".5"/><line x1="110" y1="7" x2="110" y2="19" stroke="white" strokeWidth="1.5" opacity=".9"/><line x1="104" y1="13" x2="116" y2="13" stroke="white" strokeWidth="1.5" opacity=".9"/></svg><div style={{fontFamily:'Georgia,serif',fontSize:20,fontWeight:300,color:INK,margin:'1rem 0 4px'}}>{[R.carat,R.stone,R.shape,'in',R.metal].filter(Boolean).join(' ')}</div><div style={{fontSize:13,color:INKS}}>{[R.setting,'setting'].filter(Boolean).join(' ')}</div></div><div style={{display:'flex',flexWrap:'wrap',gap:6,marginBottom:'1.25rem'}}>{[R.type,R.stone,R.shape,R.carat,R.setting,R.metal,R.band].filter(Boolean).map((t:any)=><span key={t} style={{fontSize:11,padding:'3px 10px',borderRadius:20,background:GP,color:GD,border:'1px solid '+BDR}}>{t}</span>)}</div><button onClick={submit} style={{width:'100%',background:G,border:'none',borderRadius:8,padding:13,fontSize:14,fontWeight:500,color:'#fff',cursor:'pointer',marginBottom:8,fontFamily:'inherit'}}>✉️ Submit inquiry</button><div style={{marginTop:16}}><button style={bb} onClick={prev}>← Back</button></div></div>}
    </div>
  </div>
}
